# Server Port
server.port=8080

# H2 Database Configuration (Permanent Storage)
spring.datasource.url=jdbc:mysql://localhost:3306/arshita
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect